# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test
  # ...
  
  # deploy
  deploy:
    name: "Déploiement sur le serveur de dev"
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{secrets.STAGING_SSH_USER}}
          SSH_KEY: ${{secrets.STAGING_SSH_KEY}}
          SSH_HOST: ${{secrets.STAGING_SSH_HOST}}

      - name: Pull les dernières versions de DEV
        run: ssh staging 'cd web/formateur.liliwol.fr/public_html/DEV && git fetch && git pull'
